name: muggle-gcp-files
channels:
  - conda-forge
  - default
dependencies:
  - python=3.12
  - pip
  
  - pip:
      - google-cloud-storage
  
# # To install in GCP Notebook: 
# https://cloud.google.com/vertex-ai/docs/workbench/instances/add-environment
# cd ~/muggle-code/gcp-files
# conda env create -f environment.yml
# conda activate muggle-gcp-files
# DL_ANACONDA_ENV_HOME="${DL_ANACONDA_HOME}/envs/muggle-gcp-files"
# python -m ipykernel install --prefix "${DL_ANACONDA_ENV_HOME}" --name muggle-gcp-files --display-name muggle-gcp-files
